"""
Django settings for ascots project.

Generated by 'django-admin startproject' using Django 3.2.19.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(os.path.join(BASE_DIR, '.env'))

# import os

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = 'django-insecure-oknorv_ifh62-@pyp8k#ac902j=zmj)!=3ay#59weior*w#(90'
SECRET_KEY = os.getenv('SECRET_KEY')

DEBUG = os.getenv('DJANGO_DEBUG', 'False').lower() in ('true', '1', 't')

# ALLOWED_HOSTS should be configured based on whether DEBUG is True or False
if DEBUG:
    # In development, allow all hosts for convenience
    ALLOWED_HOSTS = ['*']
else:
    # In production, be very specific about which hosts are allowed
    ALLOWED_HOSTS = ['panameraliving.app', 'www.panameraliving.app']


# ALLOWED_HOSTS = ['*','http://192.168.1.54:7000']
# ALLOWED_HOSTS_STR = os.getenv('ALLOWED_HOSTS', '')

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
 # Or your preferred location
CORS_ALLOW_ALL_ORIGINS = True

CORS_ALLOW_HEADERS = [
    'accept',
    'authorization',
    'content-type',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'Device-Type',
    'App-Version',
    'Mac-Id',
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'api',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',
    'django_celery_beat',  # Celery Beat for scheduled tasks
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'api.views.middleware.TokenValidationMiddleware',  # Custom middleware for token validation
]

ROOT_URLCONF = 'panamera_backend.urls'
AUTH_USER_MODEL = 'api.User'
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'panamera_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DATABASE_NAME'),
        'USER': os.getenv('DATABASE_USER'),
        'PASSWORD': os.getenv('DATABASE_PASSWORD'),
        'HOST': os.getenv('DATABASE_HOST'),
        # Get port from .env, provide a default value if not found, and cast to integer.
        'PORT': int(os.getenv('DATABASE_PORT')),
        'OPTIONS': {'options': '-c search_path=public'},  # Ensure schema is used
    }
}



# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


CORS_ALLOW_METHODS = [
    "GET",
    "POST",
    "PUT",
    "PATCH",
    "DELETE",
    "OPTIONS",  # THIS IS IMPORTANT
]




# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

# TIME_ZONE = 'UTC'
TIME_ZONE = 'Asia/Dubai'  # Set to Dubai time zone

USE_I18N = True

USE_L10N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'api.views.authentication.AccessTokenInvalidationAuthentication',
    ),
    'DEFAULT_PARSER_CLASSES': (
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.FormParser',
        'rest_framework.parsers.MultiPartParser',
    ),
}


SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(days=10),  # Short-lived access token
    "REFRESH_TOKEN_LIFETIME": timedelta(days=365),
    # "JTI_CLAIM": True,
    "ROTATE_REFRESH_TOKENS": True,  # Enable rotation for security
    "BLACKLIST_AFTER_ROTATION": True,  # Automatically blacklist old tokens
    "ALGORITHM": "HS256",
    "AUTH_HEADER_TYPES": ("Bearer",),
    "AUTH_TOKEN_CLASSES": ("rest_framework_simplejwt.tokens.AccessToken",),
    "USER_ID_CLAIM": 'user_id',
    "USER_ID_FIELD": 'id', # It's good practice to also define the model field name.
}



LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'detailed': {
            'format': '{levelname} {asctime} [{module}:{funcName}:{lineno}] {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'level': 'ERROR',
            'class': 'logging.FileHandler',
            'filename': '/var/log/django/error.log' if os.name != 'nt' else os.path.join(BASE_DIR, 'logs', 'error.log'),
            'formatter': 'detailed',
        },
        'clockin_clockout_file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': '/var/log/django/clockin_clockout_errors.log' if os.name != 'nt' else os.path.join(BASE_DIR, 'logs', 'clockin_clockout_errors.log'),
            'formatter': 'detailed',
        },
    },
    'loggers': {
        'django.request': {
            'handlers': ['file'],
            'level': 'ERROR',
            'propagate': False,
        },
        'api.views.check_in_view': {
            'handlers': ['clockin_clockout_file', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'api.views.check_out_view': {
            'handlers': ['clockin_clockout_file', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

# Ensure logs directory exists for local development
if os.name == 'nt':
    logs_dir = os.path.join(BASE_DIR, 'logs')
    os.makedirs(logs_dir, exist_ok=True)

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.getenv('EMAIL_HOST', 'secure.emailsrvr.com')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', '587'))
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True') == 'True'
EMAIL_USE_SSL = os.getenv('EMAIL_USE_SSL', 'False') == 'True'
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = os.getenv('EMAIL_HOST_USER')


# ============================================================================
# CELERY CONFIGURATION
# ============================================================================
# Celery broker and result backend configuration
# For production: Use Redis or RabbitMQ
# For development: Can use Redis locally or memory transport (not recommended for production)

CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL', 'redis://localhost:6379/0')
CELERY_RESULT_BACKEND = os.getenv('CELERY_RESULT_BACKEND', 'redis://localhost:6379/0')
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True  # Suppress startup warning

# Connection resilience settings
CELERY_BROKER_CONNECTION_RETRY = True  # Retry connecting to broker on connection loss
CELERY_BROKER_CONNECTION_MAX_RETRIES = 10  # Max retry attempts (None = infinite)
CELERY_BROKER_TRANSPORT_OPTIONS = {
    'visibility_timeout': 3600,  # 1 hour
    'socket_timeout': 5,  # 5 seconds socket timeout
    'socket_connect_timeout': 5,  # 5 seconds connection timeout
    'socket_keepalive': True,
    'health_check_interval': 30,  # Check connection health every 30 seconds
}
CELERY_REDIS_MAX_CONNECTIONS = 50  # Connection pool size

# Celery settings - MUST match Django timezone settings
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'Asia/Dubai'  # MUST match Django TIME_ZONE
CELERY_ENABLE_UTC = False  # MUST match Django USE_TZ = False

# Task result settings
CELERY_RESULT_EXPIRES = 86400  # Results expire after 24 hours
CELERY_TASK_TRACK_STARTED = True  # Track when tasks start
CELERY_TASK_TIME_LIMIT = 300  # 5 minutes hard time limit
CELERY_TASK_SOFT_TIME_LIMIT = 240  # 4 minutes soft time limit

# Task retry settings (default for all tasks, can be overridden per task)
CELERY_TASK_ACKS_LATE = True  # Acknowledge task after completion (safer)
CELERY_TASK_REJECT_ON_WORKER_LOST = True  # Requeue if worker dies
CELERY_TASK_DEFAULT_RETRY_DELAY = 60  # Wait 60 seconds before retry

# Worker settings
CELERY_WORKER_PREFETCH_MULTIPLIER = 4  # Number of tasks to prefetch
CELERY_WORKER_MAX_TASKS_PER_CHILD = 1000  # Restart worker after 1000 tasks (memory management)

# Beat scheduler settings (for periodic tasks)
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'

# Task routing - REMOVED for simplicity, all tasks use default queue
# This fixes ETA-based task execution issues
# CELERY_TASK_ROUTES = {}

# Optional: Set task priority
CELERY_TASK_DEFAULT_PRIORITY = 5
CELERY_TASK_ACKS_LATE = True  # Acknowledge tasks after completion, not before

# Logging for Celery tasks
CELERY_WORKER_HIJACK_ROOT_LOGGER = False
CELERY_WORKER_LOG_FORMAT = '[%(asctime)s: %(levelname)s/%(processName)s] %(message)s'
CELERY_WORKER_TASK_LOG_FORMAT = '[%(asctime)s: %(levelname)s/%(processName)s][%(task_name)s(%(task_id)s)] %(message)s'
